### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ray1919** [erasmus-center-for-biomics/Nimbus#1]
It throught out an error when I compile Nimbus
`make -C cplusplus/call
make[1]: Entering directory '/BASEDIR/Nimbus/cplusplus/call'
mkdir -p bin/
g++  build/call.o  build/read_provider.o  build/alignment_functions.o  build/mpileup.o  build/aspects.o  build/refsequence.o  build/main.o  build/sample.o  build/cigar.o -g -L/usr/lib64 -std=c++0x \
        -pthread \
        ${HTS_LIB} -lm -lz -lcurl -llzma -lbz2 \
        -lboost_program_options \
        -o bin/nimbus_call
/usr/bin/ld: /BASEDIR/samtools/samtools-1.7/htslib-1.7/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha1@@OPENSSL_1.0.0'
//lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'caller' failed
make[1]: *** [caller] Error 1
make[1]: Leaving directory '/BASEDIR/Nimbus/cplusplus/call'
Makefile:19: recipe for target 'call' failed
make: *** [call] Error 2
`
I googled the error and solved the error by adding "-lcrypto" to the command. I don't know whether it is a  single case, otherwise you could fix the bug in Makefile.

**Comment by erasmus-center-for-biomics** [comment]
Dear Ray, 

I have heard of the `-lcrypto` error before. To my knowledge, it only occurs on virtual machines running in the cloud. I can make a specific Makefile for use with cloud instances. 

I assume that most people will not have crypto-dev installed on their regular servers.

with kind regards, 

Rutger

**Comment by ray1919** [comment]
Thank you for your reply.
