### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ray1919** [erasmus-center-for-biomics/Nimbus#2]
After installed nimbus, the nimbus_trim & nimbus_call run with same error:

`terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed
Aborted (core dumped)`

I reinstalled the boost, and it does not help

**Comment by erasmus-center-for-biomics** [comment]
Hi Ray, 

I have not yet encountered this error before: I will look into it.

Could you share the Linux OS and version of the machine on which you are running Nimbus? 
Also the version of BOOST might be handy to recreate this errror.

with kind regards, 

Rutger

**Comment by ray1919** [comment]
Finally I made it by compiling it in a different Ubuntu desktop. It works fine after I copied it to my own desktop.

The Linux OS is Ubuntu 16.04, kernel:

Linux ub0 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 GNU/Linux

BOOST 1.58, 1.67
