### ISSUE TITLE
the format of bed file

### ISSUE THREAD

**Issue by weibochen** [erasmus-center-for-biomics/Nimbus#3]
i write a bed file, is it correct?
`chr12	15239647	15239772`
it contains chrome, start and end, is it need other infomations?
is there a example?

**Comment by erasmus-center-for-biomics** [comment]
Dear weibochen,

Nimbus also requires the strand information, so we only support 6 column BED files. For the BED entry to be usable in Nimbus, you would need to add a name, score and a strand. 

For example: `chr12\t15239647\t15239772\tsome_name\t.\t+`

Also note that the fields should be tab-delimited (indicated with the `\t` character).

with kind regards,

Rutger
